apiVersion: v1
kind: Namespace
metadata:
  name: Dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-demo-app
  template:
    metadata:
      labels:
        app: the-demo-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: the-demo-app
        image: docker.io/aboulmagd/webappfordemo:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "redis-back"
---
apiVersion: v1
kind: Service
metadata:
  name: the-demo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: the-demo-app
